drop table TASK_ASO;
drop table USTAVKA_PARAM_SYS;
drop table MEAS_PARAM_SYS;
drop table SIGN_SYS;
drop table PASSPORT_PARAM_SYS;
drop table TYPE_SIGNAL_TABLE;

-- create SEQUENCE SIGN_SYS

create table TYPE_SIGNAL_TABLE(
ID_SIGNAL Integer,
TEXT_SIGNAL VARCHAR(50),
primary key(ID_SIGNAL)
);

create table TASK_ASO
(
DATE_TASK DATE,
ID_SENSORS Integer,
EXPDATE DATE,
primary key(ID_SENSORS)
);

create table USTAVKA_PARAM_SYS
(
ID_USTAVKA VARCHAR(50),
DATE_USTAVKA DATE,
VALUE_USTAVKA_PRE FLOAT,
VALUE_USTAVKA_AV FLOAT,
COEFF_RETURN FLOAT,
primary key(ID_USTAVKA)
);

create table MEAS_PARAM_SYS
(
ID_SENSORS INTEGER,
STATUS_SENSORS INTEGER,
SORT_SENSORS INTEGER,
DATE_MEAS DATE,
TIME_MEAS TIME,
SORT_MEAS INTEGER,
VALUE_MEAS float,
TRUST_MEAS INTEGER,
WORK_SENSORS  boolean,
primary key(ID_SENSORS)
foreign key(ID_SENSORS) references  PASPORT_PARAM_SYS(ID_SENSORS) on delete cascade
);

create table SIGN_SYS
(
ID_SIGN INTEGER AUTO_INCREMENT,
DATE_SIGN DATE,
TIME_SIGN TIME,
SORT_SIGN INTEGER,
TEXT_SIGN INTEGER,
ID_SENSORS  INTEGER,
primary key(ID_SIGN)
foreign key(ID_SENSOR) references  PASPORT_PARAM_SYS(ID_SENSORS) on delete cascade
);

create table PASSPORT_PARAM_SYS
(
SENSORS_OA_TYPE VARCHAR(40),
SENSORS_OA_ELEMENTS VARCHAR(40),
SORT_MEAS VARCHAR(100),
TYPE_OF_MEAS VARCHAR(50),
SENSORS_GROUP VARCHAR(40),
SENSORS_TYPE VARCHAR(40),
ID_SENSORS INTEGER,
X_VALUE FLOAT,
Y_VALUE FLOAT,
primary key(ID_SENSORS)
);