drop table documents;
drop table sensors;
drop table SIGN_SYS;
drop table TYPE_SIGNAL_TABLE;
drop table PASSPORT_PARAM_SYS;

create table PASSPORT_PARAM_SYS
(
SENSORS_OA_TYPE VARCHAR(40),
SENSORS_OA_ELEMENTS VARCHAR(40),
SORT_MEAS VARCHAR(100),
TYPE_OF_MEAS VARCHAR(50),
SENSORS_GROUP VARCHAR(40),
SENSORS_TYPE VARCHAR(40),
ID_SENSORS INTEGER,
primary key(ID_SENSORS)
);


create table TYPE_SIGNAL_TABLE(
ID_SIGNAL Integer,
TEXT_SIGNAL VARCHAR(50),
primary key(ID_SIGNAL)
)
ALTER TABLE TYPE_SIGNAL_TABLE CONVERT TO CHARACTER SET 'utf8';

create table SIGN_SYS
(
ID_SIGN INTEGER AUTO_INCREMENT,
DATE_SIGN DATE,
TIME_SIGN TIME,
SORT_SIGN INTEGER,
TEXT_SIGN Integer,
ID_SENSORS  INTEGER,
primary key(ID_SIGN)
);
ALTER TABLE SIGN_SYS  CONVERT TO CHARACTER SET 'utf8';

create table sensors
(
   ID_MEAS INTEGER AUTO_INCREMENT,
   DATE_MEAS DATE,
   TIME_MEAS TIME, 
   VALUE_MEAS float,
   ID_SENSOR INTEGER,
   primary key(ID_MEAS),
   foreign key(ID_SENSOR) references  PASPORT_PARAM_SYS(ID_SENSORS) on delete cascade
);

create table documents
(
  ID_DOC INTEGER AUTO_INCREMENT,
  FILE_NAME_FULL  VARCHAR(500),
  FILE_NAME VARCHAR(256),
  DISCRIPTION VARCHAR(500),
  primary key(ID_DOC)
);



